[versions]
mariaDBJavaClientVersion = "3.1.0"
lombokVersion = "1.18.30"
junitVersion = "4.13.2"
springFrameworkBootVersion = "4.1.1"
springDependencyManagementVerrsion = "1.1.0"

[libraries]
mariaDBJavaClient = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariaDBJavaClientVersion" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombokVersion" }
junit = { module = "junit:junit", version.ref = "junitVersion" }

[bundles]
unitTestBundle = ["junit"]

[plugins]
springFrameworkBoot = { id = "org.springframework.boot", version.ref = "springFrameworkBootVersion" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagementVerrsion" }
